export const schools = [
  { id: "nyu", name: "New York University", city: "New York", area: "Manhattan" },
  { id: "columbia", name: "Columbia University", city: "New York", area: "Morningside Heights" },
  { id: "cornell", name: "Cornell University", city: "Ithaca", area: "Collegetown" },
  { id: "harvard", name: "Harvard University", city: "Cambridge", area: "Harvard Square" },
  { id: "mit", name: "Massachusetts Institute of Technology", city: "Cambridge", area: "Kendall Square" },
  { id: "bu", name: "Boston University", city: "Boston", area: "Fenway-Kenmore" },
  { id: "northeastern", name: "Northeastern University", city: "Boston", area: "Fenway" },
  { id: "tufts", name: "Tufts University", city: "Medford", area: "Medford/Somerville" },
  { id: "yale", name: "Yale University", city: "New Haven", area: "Downtown" },
  { id: "princeton", name: "Princeton University", city: "Princeton", area: "Princeton" },
  { id: "upenn", name: "University of Pennsylvania", city: "Philadelphia", area: "University City" },
  { id: "cmu", name: "Carnegie Mellon University", city: "Pittsburgh", area: "Oakland" },
  { id: "pitt", name: "University of Pittsburgh", city: "Pittsburgh", area: "Oakland" },
  { id: "uchicago", name: "University of Chicago", city: "Chicago", area: "Hyde Park" },
  { id: "northwestern", name: "Northwestern University", city: "Evanston", area: "Evanston" },
  { id: "umich", name: "University of Michigan", city: "Ann Arbor", area: "Central Campus" },
  { id: "uiuc", name: "University of Illinois Urbana-Champaign", city: "Urbana-Champaign", area: "Campustown" },
  { id: "purdue", name: "Purdue University", city: "West Lafayette", area: "Chauncey Village" },
  { id: "uw-madison", name: "University of Wisconsin-Madison", city: "Madison", area: "Downtown Madison" },
  { id: "umn", name: "University of Minnesota Twin Cities", city: "Minneapolis", area: "Dinkytown" },
  { id: "osu", name: "Ohio State University", city: "Columbus", area: "University District" },
  { id: "ut-austin", name: "University of Texas at Austin", city: "Austin", area: "West Campus" },
  { id: "rice", name: "Rice University", city: "Houston", area: "Rice Village" },
  { id: "texas-am", name: "Texas A&M University", city: "College Station", area: "Northgate" },
  { id: "usc", name: "University of Southern California", city: "Los Angeles", area: "University Park" },
  { id: "ucla", name: "UCLA", city: "Los Angeles", area: "Westwood" },
  { id: "uc-berkeley", name: "UC Berkeley", city: "Berkeley", area: "Southside" },
  { id: "stanford", name: "Stanford University", city: "Stanford", area: "Palo Alto" },
  { id: "caltech", name: "California Institute of Technology", city: "Pasadena", area: "Pasadena" },
  { id: "ucsd", name: "UC San Diego", city: "San Diego", area: "La Jolla" },
  { id: "uci", name: "UC Irvine", city: "Irvine", area: "University Town Center" },
  { id: "ucsb", name: "UC Santa Barbara", city: "Santa Barbara", area: "Isla Vista" },
  { id: "uc-davis", name: "UC Davis", city: "Davis", area: "Downtown Davis" },
  { id: "uw", name: "University of Washington", city: "Seattle", area: "University District" },
  { id: "duke", name: "Duke University", city: "Durham", area: "Duke University" },
  { id: "unc", name: "University of North Carolina at Chapel Hill", city: "Chapel Hill", area: "Downtown Chapel Hill" },
  { id: "gatech", name: "Georgia Institute of Technology", city: "Atlanta", area: "Midtown" },
  { id: "emory", name: "Emory University", city: "Atlanta", area: "Druid Hills" },
  { id: "uf", name: "University of Florida", city: "Gainesville", area: "University Park" },
  { id: "asu", name: "Arizona State University", city: "Tempe", area: "Downtown Tempe" },
  { id: "ubc", name: "University of British Columbia", city: "Vancouver", area: "Point Grey" },
];
